"""Synthetic public-safe seed records."""

from __future__ import annotations

from .models import PrimitiveRecord, ServiceEndpoint, ServiceRecord, TemplateSlot


SEED_PRIMITIVES: tuple[PrimitiveRecord, ...] = (
    PrimitiveRecord(
        primitive_id="prim.web.discover_pages.v1",
        label="web.discover_pages",
        input_contract="QuerySpec",
        output_contract="SourcePageSet",
        effects=("network_read",),
        proof_obligations=("implementation_artifact", "network_fixture"),
        promotion_blockers=("seed_metadata_only",),
        source_refs=("seed:web.discover",),
        search_text="discover authoritative web source pages query source pages",
    ),
    PrimitiveRecord(
        primitive_id="prim.web.fetch_documents.v1",
        label="web.fetch_documents",
        input_contract="SourcePageSet",
        output_contract="HtmlDocumentSet",
        effects=("network_read",),
        proof_obligations=("implementation_artifact", "network_fixture"),
        promotion_blockers=("seed_metadata_only",),
        source_refs=("seed:web.fetch",),
        search_text="fetch html documents from source pages",
    ),
    PrimitiveRecord(
        primitive_id="prim.html.extract_rate_texts.v1",
        label="html.extract_rate_texts",
        input_contract="HtmlDocumentSet",
        output_contract="list[RawRateText]",
        proof_obligations=("implementation_artifact", "html_fixture"),
        promotion_blockers=("seed_metadata_only",),
        source_refs=("seed:html.extract",),
        search_text="extract interest rate text from html tables jurisdiction rates",
    ),
    PrimitiveRecord(
        primitive_id="prim.rate.normalize_one.v1",
        label="rate.normalize_one",
        input_contract="RawRateText",
        output_contract="NormalizedRate",
        remix_tools=("map_sequence",),
        proof_obligations=("implementation_artifact", "normalization_fixture"),
        promotion_blockers=("seed_metadata_only",),
        source_refs=("seed:rate.normalize_one",),
        search_text="normalize one interest rate text jurisdiction normalized rate",
    ),
    PrimitiveRecord(
        primitive_id="prim.rate.normalize_batch.v1",
        label="rate.normalize_batch",
        input_contract="list[RawRateText]",
        output_contract="list[NormalizedRate]",
        proof_obligations=("implementation_artifact", "normalization_fixture"),
        promotion_blockers=("seed_metadata_only",),
        source_refs=("seed:rate.normalize_batch",),
        search_text="batch normalize interest rate texts jurisdiction normalized rates",
    ),
    PrimitiveRecord(
        primitive_id="prim.validation.crosscheck_rates.v1",
        label="validation.crosscheck_rates",
        input_contract="list[NormalizedRate]",
        output_contract="ProvenancedRateTable",
        proof_obligations=("implementation_artifact", "provenance_fixture"),
        promotion_blockers=("seed_metadata_only",),
        source_refs=("seed:validation.crosscheck",),
        search_text="crosscheck normalized rates provenance source validation",
    ),
    PrimitiveRecord(
        primitive_id="prim.output.emit_json.v1",
        label="output.emit_json",
        input_contract="ProvenancedRateTable",
        output_contract="OutputArtifact",
        proof_obligations=("implementation_artifact", "output_fixture"),
        promotion_blockers=("seed_metadata_only",),
        source_refs=("seed:output.emit_json",),
        search_text="emit json output artifact provenanced table",
    ),
    PrimitiveRecord(
        primitive_id="candidate.csv.profile_columns.v0",
        label="csv.profile_columns",
        input_contract="CsvProfileInput",
        output_contract="CsvProfileReport",
        readiness="R6_executable_proven",
        proof_obligations=("packaged_fixture_proof", "source_digest"),
        promotion_blockers=("governance_promotion_required",),
        source_refs=("python:aidevobserver_fabric.primitives.csv_profile_columns",),
        search_text="csv profile rows columns warehouse ingestion delimiter table",
    ),
    PrimitiveRecord(
        primitive_id="candidate.document.extract_schema_fields.v0",
        label="document.extract_schema_fields",
        input_contract="ParsedDocument",
        output_contract="RawFieldSet",
        proof_obligations=("source_span_fixture", "schema_validation"),
        promotion_blockers=("candidate_only", "needs_license_review"),
        source_refs=("seed:document.schema",),
        search_text="document schema field extraction json source spans parsed document",
    ),
    PrimitiveRecord(
        primitive_id="candidate.agent.detect_retry_loop.v0",
        label="observer.detect_retry_loop",
        input_contract="SessionEventSet",
        output_contract="AgentLoopFindingSet",
        proof_obligations=("session_fixture", "false_positive_control"),
        promotion_blockers=("candidate_only", "needs_benchmark"),
        source_refs=("seed:observer.loop",),
        search_text="detect repeated coding agent retry loop session failure wasted context",
    ),
    PrimitiveRecord(
        primitive_id="candidate.social.facebook_rapidapi_fetch_posts.v0",
        label="social.facebook_rapidapi_fetch_posts",
        input_contract="FacebookSourceSet",
        output_contract="RawSocialPostSet",
        effects=("network_read", "external_api_call"),
        memory="artifact_ref",
        cache="ttl",
        proof_obligations=("provider_fixture", "redacted_key_scan", "response_schema_fixture"),
        promotion_blockers=("candidate_only", "needs_provider_selection", "needs_terms_review"),
        source_refs=("examples:facebook_sources", "examples:rapidapi_facebook_provider"),
        search_text="facebook page scraper rapidapi fetch posts social media newsletters publications pages",
    ),
    PrimitiveRecord(
        primitive_id="candidate.social.normalize_posts.v0",
        label="social.normalize_posts",
        input_contract="RawSocialPostSet",
        output_contract="NormalizedSocialPostSet",
        proof_obligations=("response_shape_fixture", "schema_validation"),
        promotion_blockers=("candidate_only", "needs_provider_fixtures"),
        source_refs=("src:social_ingest.normalize_posts",),
        search_text="normalize facebook social posts text author metrics permalink created time",
    ),
    PrimitiveRecord(
        primitive_id="candidate.social.posts_to_primitive_drafts.v0",
        label="social.posts_to_primitive_drafts",
        input_contract="NormalizedSocialPostSet",
        output_contract="PrimitiveDraftSet",
        effects=("llm_candidate_summary",),
        proof_obligations=("human_review", "license_review", "duplicate_detection"),
        promotion_blockers=("candidate_only", "serves_truth_false", "needs_review"),
        source_refs=("src:social_ingest",),
        search_text="distill newsletters publications social posts into primitive drafts candidate evidence",
    ),
)


TEMPLATE_SLOTS: dict[str, tuple[TemplateSlot, ...]] = {
    "profile_tabular_data": (
        TemplateSlot("profile", "profile tabular columns", "CsvProfileInput", "CsvProfileReport"),
    ),
    "normalize_regulatory_rates": (
        TemplateSlot("discover", "discover source pages", "QuerySpec", "SourcePageSet"),
        TemplateSlot("fetch", "fetch documents", "SourcePageSet", "HtmlDocumentSet"),
        TemplateSlot("extract", "extract raw rate text", "HtmlDocumentSet", "list[RawRateText]"),
        TemplateSlot("normalize", "normalize rate texts", "list[RawRateText]", "list[NormalizedRate]", ("map_sequence",)),
        TemplateSlot("validate", "crosscheck provenance", "list[NormalizedRate]", "ProvenancedRateTable"),
        TemplateSlot("emit", "emit artifact", "ProvenancedRateTable", "OutputArtifact"),
    ),
    "extract_schema_fields": (
        TemplateSlot("extract_fields", "extract fields with spans", "ParsedDocument", "RawFieldSet"),
    ),
    "review_agent_session": (
        TemplateSlot("detect_loop", "detect agent retry loop", "SessionEventSet", "AgentLoopFindingSet"),
    ),
    "ingest_social_posts": (
        TemplateSlot("fetch_posts", "fetch posts through configured provider", "FacebookSourceSet", "RawSocialPostSet"),
        TemplateSlot("normalize_posts", "normalize social post records", "RawSocialPostSet", "NormalizedSocialPostSet"),
        TemplateSlot("draft_primitives", "distill posts into primitive drafts", "NormalizedSocialPostSet", "PrimitiveDraftSet"),
    ),
}


TEMPLATE_IDS = {
    "profile_tabular_data": "template.data.profile_csv_artifact.v0",
    "normalize_regulatory_rates": "template.web.scrape_provenanced_rates.v0",
    "extract_schema_fields": "template.document.extract_schema_fields.v0",
    "review_agent_session": "template.observer.review_agent_session.v0",
    "ingest_social_posts": "template.social.ingest_posts_to_primitive_drafts.v0",
}


SERVICES: tuple[ServiceRecord, ...] = (
    ServiceRecord(
        service_id="svc.primitive_search.v0",
        label="Primitive Search",
        purpose="Search primitive records with blockers, hybrid lanes, and RRF.",
        readiness="R6_searchable",
        mode="local_readonly",
        consumes=("PrimitiveSearchQuery",),
        produces=("HybridPrimitiveSearchResult", "CandidateBundle"),
        gates=("read_only", "candidate_advice_only"),
        endpoints=(
            ServiceEndpoint(
                route="/capabilities/search",
                method="GET",
                input_contract="PrimitiveSearchQuery",
                output_contract="HybridPrimitiveSearchResult",
                command="aidevobserver-fabric search --query TEXT",
                description="Run blocker-first hybrid primitive search.",
            ),
        ),
    ),
    ServiceRecord(
        service_id="svc.route_bundles.v0",
        label="Route Bundles",
        purpose="Return template-slot candidate bundles for compact LLM planning.",
        readiness="R6_searchable",
        mode="local_readonly",
        consumes=("BundleListQuery",),
        produces=("CandidateBundleSet",),
        gates=("read_only", "compiler_validation_required"),
        endpoints=(
            ServiceEndpoint(
                route="/bundles",
                method="GET",
                input_contract="BundleListQuery",
                output_contract="CandidateBundleSet",
                command="aidevobserver-fabric bundles",
                description="List materialized candidate bundles.",
            ),
        ),
    ),
    ServiceRecord(
        service_id="svc.agent_discovery.v0",
        label="Agent Discovery",
        purpose="Expose compact service awareness to agents.",
        readiness="R6_searchable",
        mode="local_readonly",
        consumes=("AgentDiscoveryQuery",),
        produces=("AgentDiscoveryView",),
        gates=("read_only", "awareness_not_authorization"),
        endpoints=(
            ServiceEndpoint(
                route="/agents/discovery",
                method="GET",
                input_contract="AgentDiscoveryQuery",
                output_contract="AgentDiscoveryView",
                command="aidevobserver-fabric services --compact",
                description="Return compact service discovery view.",
            ),
        ),
    ),
    ServiceRecord(
        service_id="svc.social_ingest.v0",
        label="Social Source Ingest",
        purpose="Plan or run candidate-only social post ingestion through a configured RapidAPI provider.",
        readiness="R4_candidate_runtime",
        mode="local_explicit_network",
        consumes=("FacebookSourceSet", "RapidApiProviderSpec"),
        produces=("RapidApiRequestPlan", "NormalizedSocialPostSet"),
        gates=("candidate_only", "requires_env_key", "terms_review_required"),
        endpoints=(
            ServiceEndpoint(
                route="cli:rapidapi-plan",
                method="CLI",
                input_contract="RapidApiProviderSpec+FacebookSourceSet",
                output_contract="RapidApiRequestPlan",
                command="aidevobserver-fabric rapidapi-plan --provider-config examples/rapidapi_facebook_provider.example.json",
                description="Return redacted RapidAPI request plans for configured social sources.",
            ),
            ServiceEndpoint(
                route="cli:rapidapi-scrape",
                method="CLI",
                input_contract="RapidApiProviderSpec+FacebookSourceSet",
                output_contract="NormalizedSocialPostSet",
                command="RAPIDAPI_KEY=... aidevobserver-fabric rapidapi-scrape --provider-config PROVIDER.json",
                description="Fetch and normalize posts through a selected RapidAPI provider.",
            ),
        ),
    ),
    ServiceRecord(
        service_id="svc.primitive_factory.v0",
        label="Primitive Factory",
        purpose="Generate candidate genomes, mutations, crossovers, benchmark estimates, and fitness views from primitive records.",
        readiness="R4_candidate_factory",
        mode="local_readonly",
        consumes=("PrimitiveRecordSet",),
        produces=("PrimitiveGenomeSet", "MutationRecordSet", "FitnessRecordSet"),
        gates=("candidate_only", "proof_required_for_promotion"),
        endpoints=(
            ServiceEndpoint(
                route="/factory",
                method="GET",
                input_contract="PrimitiveRecordSet",
                output_contract="EvolutionaryFactorySnapshot",
                command="aidevobserver-fabric factory --compact",
                description="Return a candidate-only primitive lifecycle factory view.",
            ),
            ServiceEndpoint(
                route="/factory/lineage",
                method="GET",
                input_contract="PrimitiveId",
                output_contract="PrimitiveLineage",
                command="aidevobserver-fabric factory-lineage PRIMITIVE_ID",
                description="Return mutation children and contract-aligned crossovers for one primitive.",
            ),
        ),
    ),
)
